language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - mkdir mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script: php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
  fast_finish: true
